import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Medium Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
title = "Alacritty"

[window.dimensions]
columns = 133
lines = 40
